### ISSUE TITLE
No Hot Module Replacement?

### ISSUE THREAD

**Issue by M0ns1gn0r** [fable-elmish/templates#14]
I've noticed the browser refreshes after I made changes to the sources, but the current state gets lost at this moment. Apparently, there is no [HMR ](https://webpack.js.org/concepts/hot-module-replacement/) in this template.

Can this be improved?

**Comment by MangelMaxime** [comment]
Yes HMR is possible to implement.

Alfonso show an example of it with Fable 1.0 [here](https://github.com/fable-compiler/hmr-sample/blob/master/src/main.fsx#L21-L23).

Also, at the time I made a very basic (dirty) implementation of HMR with Fable-Arch (ancestor of Elmish).
http://fable.io/fable-arch/#/docs?fileName=hmr

If you need it you can add a PR to the template :) (the one call react-demo)

**Comment by alfonsogarciacaro** [comment]
Yes, I had that sample to check HMR with Webpack but IMHO HMR is not worth the effort, the way to use it with the react-loader is constantly changing and it's a lot of work to implement it right. And then sometimes you get conflicts modules if you implement events or observables.

For Elmish apps it's should be much easier to just save the state every time in the Browser storage and load it after a refresh. I think there's already a function somewhere to do that in one line when starting the program. This has the advantage it will work for final users too (if that's not what you intend you can surround the code to save the state with `#if DEBUG` directives).

**Comment by et1975** [comment]
If you take a look at TODO sample, it's written in a way that stores the state on each state update.
The `init` function checks to see if there's a state in local storage and if there is it picks up from there. One caveat though: `init` of a program augmented with Navigation (`Program.toNavigable`) forces the arguments of the `init` to take the initial route, so you'll have to declare the `init` like this:
```fsharp
let init (storedState,route) =
// do the init logic
```

and add the persistence in with something like
```fsharp
let loadState route =
// read the stored state
(state,route)
```

then pass the persistence-enabled init into the Program:
```fsharp
Program.mkProgram (loadState >> init) update
//etc
```

**Comment by MangelMaxime** [comment]
@et1975 @forki Should we try to add this feature the `demo` templates ?

Also @bentayloruk_twitter was working on something similar. (Quote from gitter)

Morning all.

>  Has anyone had a crack at model state persistence, so after a hot reload, you get your model back? Would be useful for when working on complex forms etc. Ala https://github.com/ccapndave/elm-hot-reload
> In Elmish.
> 
> @forki I got kind of close to retaining the model state with Elmish init & update wrapper functions, but I've got a React Form Input uncontrolled warning message to deal with. The form values are in the reloaded model, but they are not rendering in the inputs (they are blank, despite the view setting the Value attribute). Weirdly their validity status is reflected in the CSS styling, so that is working! Hopefully, I can get it to work. Looking like this so far:
> 
> 

```fs
let update msg model =
    match msg, model.PageModel with
    | HotInit, PromosModel _ -> model, Cmd.ofMsg (AppMsg.PromosMsg Promos.Msg.Init)
    // Clipped...

[<Literal>]
let ModelStorageKey = "hot-init-store"

let hotInit init result =
    let model = Browser.localStorage.getItem(ModelStorageKey) |> unbox |> Microsoft.FSharp.Core.Option.map (JS.JSON.parse >> unbox<Model>)
    match model with 
    | Some model ->
        System.Console.WriteLine("Hot init.")
        model, Cmd.ofMsg AppMsg.HotInit
    | None ->
        System.Console.WriteLine("Cold init.")
        init result

let hotUpdate update (msg:AppMsg) (model:Model) =
    let model, cmd = update msg model
    Browser.localStorage.setItem(ModelStorageKey, JS.JSON.stringify model)
    model, cmd

// App
Program.mkProgram (hotInit init) (hotUpdate update) view
|> Program.toNavigable (parseHash pageParser) urlUpdate
|> Program.withConsoleTrace
|> Program.withReact "elmish-app"
|> Program.run
```

**Comment by forki** [comment]
💋 :

**Comment by forki** [comment]
I wonder if hotUpdate should go to Program.with`HotUpdate`

**Comment by MangelMaxime** [comment]
@forki Yes, if we provide HMR I would encapsulate it like via `Program.*` like we do with the debugger.

Like so, we could have:

```fs
Program.mkProgram init update view
|> Program.toNavigable (parseHash pageParser) urlUpdate
|> Program.withReact "elmish-app"
#if DEBUG
|> Program.withConsoleTrace
|> Program.withDebugger
|> Program.withHMR
#endif
|> Program.run
```

**Comment by forki** [comment]
`|> Program.withAllTheHottestShitThereIs`
