### ISSUE TITLE
PaketExePath on macOS 10.12

### ISSUE THREAD

**Issue by pro100filipp** [fable-elmish/templates#15]
When running `dotnet restore` on dotnet v2 it fails with
`Cannot open assembly '': No such file or directory.
/Users/philipp/Projects/FSharp/awesome/.paket/Paket.Restore.targets(16,5): error MSB3073: The c
ommand "/Library/Frameworks/Mono.framework/Commands/mono --runtime=v4.0.30319 "" restore --proj
ect "/Users/philipp/Projects/FSharp/awesome/awesome.fsproj" --target-framework netstandard1.6"
exited with code 2. [/Users/philipp/Projects/FSharp/awesome/awesome.fsproj]`

The problem is in missing XML variable condition in Paket.Restore.targets:  
`<PaketExePath Condition=" '$(PaketExePath)' == '' ">$(PaketToolsPath)paket.exe</PaketExePath>`

The issue occurs only on dotnet v2.

**Comment by alfonsogarciacaro** [comment]
@forki Could you please have a look? Cheers!

**Comment by forki** [comment]
@pro100filipp I don't really see the issue. https://github.com/fable-elmish/templates/pull/16 is newest version. can you point me to the concrete issue?

**Comment by MangelMaxime** [comment]
Should be solved by: https://github.com/fable-elmish/templates/commit/00d87acc6f5f3ab114dbb4a9d636e47757f514c2

**Comment by MangelMaxime** [comment]
Should be solve by: https://github.com/fable-elmish/templates/commit/00d87acc6f5f3ab114dbb4a9d636e47757f514c2

Waiting @forki confirmation :)

**Comment by forki** [comment]
I can't confirm since it could not repro the issue after I delete my user folder crap

**Comment by MangelMaxime** [comment]
@pro100filipp Could you give it a try ?

**Comment by pro100filipp** [comment]
@MangelMaxime @forki just tried it on my macOS 10.12. Works fine. Thank you! Can be closed.
