### ISSUE TITLE
Move classList to react lib or elmish or elsewhere

### ISSUE THREAD

**Issue by forki** [fable-elmish/templates#2]
that classList helper function in Global.fs should not be here.

**Comment by MangelMaxime** [comment]
I would vote for React lib

**Comment by forki** [comment]
Please go ahead. @et1975 or myself will probably merge it ASAP

Am 18.04.2017 10:22 vorm. schrieb "Maxime Mangel" <notifications@github.com

**Comment by et1975** [comment]
CSS manipulations don't belong in either React or Elmish. In JS-land it's a separate lib. There was some talk about doing styles in F# (instead of CSS/SCSS), perhaps we should start a lib for that.

**Comment by forki** [comment]
Good point. My only issue was that I don't really want to see this in the
sample.

Am 18.04.2017 1:54 nachm. schrieb "Eugene Tolmachev" <
notifications@github.com>:

**Comment by MangelMaxime** [comment]
I am closing this issue as we moved the classLib function to React.

If someone create an F# styling lib etc. it will still be the time to update the template from there.
