### ISSUE TITLE
Have the templates use webpack 3

### ISSUE THREAD

**Issue by Kurren123** [fable-elmish/templates#22]
I haven't tried using [Webpack 3](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b) yet but it [looks like there may be no issues with Fable](https://github.com/fable-compiler/Fable/issues/1017). If its as straight forward as doing the npm upgrade and testing then I'm happy to do that.

**Comment by MangelMaxime** [comment]
Should be available in the latest version now.
