### ISSUE TITLE
Is there a template for dotnet core 2?

### ISSUE THREAD

**Issue by mrkaspa** [fable-elmish/templates#25]

**Comment by MangelMaxime** [comment]
Not yet, we are still in a bit of testing dotnet core 2 and also how we want to work with the libraries.

**Comment by kerams** [comment]
I'd like to see this too.

**Comment by mrkaspa** [comment]
Fable support for dotnet core 2 has been released https://github.com/fable-compiler/Fable/issues/1108

**Comment by MangelMaxime** [comment]
Both templates have been updated to dotnet core 2.
