### ISSUE TITLE
Issue with `-` in name

### ISSUE THREAD

**Issue by evilz** [fable-elmish/templates#28]
When creating a project that contains `-` in the project name, it will be replace by underscore.

- Sln is wrong
- webpack.config is wrong

Folder and fsproj are OK.

**Comment by alfonsogarciacaro** [comment]
Yeah, this affects the Fable.Template too (also with a `.` I believe). If I managed to find the link I'll paste it here, but IIRC the solution was to also use a `-` in the placeholder project name (within the template).

**Comment by MangelMaxime** [comment]
This is duplicate with #7 which contains references to issues with dotnet/templating issues
