### ISSUE TITLE
creating a project with "-" in it breaks the build

### ISSUE THREAD

**Issue by isaacabraham** [fable-elmish/templates#34]
I created a project called `elmish-101`. This fails, I think when you run the yarn step - fails to compile. It seems to replace the `-` with a `_` in the path to the project.

Sorry - don't have the error with me any more but it's easy to repro.

**Comment by MangelMaxime** [comment]
This is related to #7 and it is caused by dotnet template engine.

The solution is to manually fix [webpack.config.js](https://github.com/fable-elmish/templates/blob/master/src/react-demo/Content/webpack.config.js#L25) or do not use `-` and `.` in your project name...

**Comment by isaacabraham** [comment]
Understood. Perhaps some warning somewhere / somehow? or in the docs?

**Comment by MangelMaxime** [comment]
@isaacabraham Would it make sense to add it to the README ? With some warnings sign ?

One question, what was your reference to learn how to use the template ? The readme ? A blog post ? 
This is just to determine, where we should place it.

**Comment by isaacabraham** [comment]
I just followed the readme, yeah. IMHO that's the best place to put it as it's directly coupled with the code in the repo itself with some warnings, yes. The error is kind of hard to see - you get a load of red and unless you read the details careful it's easy to miss. In the worse case, this gives Fable a bad reputation because "it doesn't work" when it's not that at all.

**Comment by MangelMaxime** [comment]
Ok thanks for the answer.

I added a warning in the README acffd3dc8f8f85ac99f0950da0030af237b65325

**Comment by alfonsogarciacaro** [comment]
I heard once that it can be fixed by using a `-` and/or `.` in the project name placeholder, but I haven't tried, I'll try to check for the next release of the simple template. If it works maybe we can just remove the placeholder from the main file module name, as F# doesn't accept hyphens there.
