### ISSUE TITLE
Fable.Template.Elmish.React throws websocket related errors after fresh install

### ISSUE THREAD

**Issue by sqeezy** [fable-elmish/templates#36]
# Repro:
- install Fable.Template.Elmish.React template via dotnet-cli(2.0.3)
- create new project via dotnet-cli
- yarn install
- dotnet restore in src/
- dotnet fable npm-start

When I visit localhost:8080 I see the sample app, but in the console I get the following errors on each interaction with the site.

# Error:
```
sctransport.js:10 WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
```
WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by MangelMaxime** [comment]
This is because, the template is setup to use Elmish.Debugger.

Easy way to fix it, is to remove the [debugger line](https://github.com/fable-elmish/templates/blob/master/src/react/Content/src/App.fs#L76)

Or install the redux dev tool extensions : https://github.com/zalmoxisus/redux-devtools-extension

**Comment by sqeezy** [comment]
I installed the extension. That worked fine. Errors are gone.

I still do not get the update messages in the console. This maybe a problem of my chrome config, I'm farily new to this. Any idea what I do wrong here?

**Comment by MangelMaxime** [comment]
If you want the message print in the console, add this line `Program.withConsoleTrace` to your app start function.

**Comment by sqeezy** [comment]
Works like a charm. Thank you very much.

**Comment by MaxWilson** [comment]
Thank you! This worked for me.
