### ISSUE TITLE
React demo crashes in IE11

### ISSUE THREAD

**Issue by markpattison** [fable-elmish/templates#37]
REPRO STEPS

In VS Code:

```
dotnet new fable-elmish-react -n awesome
cd awesome
yarn install
cd src
dotnet restore
dotnet fable yarn-start
```

Navigate to http://localhost:8080/ in Firefox - works fine.
Do the same in IE11 - blank page.

Debugging the JS reveals an "Object expected" error but I can't get any further than that.

**Comment by MangelMaxime** [comment]
Please try update the dependencies to latest version.

If it's not working,  I will need to check the polyfill.

**Comment by markpattison** [comment]
Thanks @MangelMaxime .

I updated packages using paket as follows and still get the same error.  Sorry I can't help more - I know nothing about JS or polyfills (which is why Fable is so awesome...)

```
Downloading Fable.Import.Browser 0.1.1
Downloading Fable.Elmish 1.0.0
Downloading Fable.Elmish.React 1.0.0
Downloading Fable.Elmish.Browser 1.0.0
Downloading Fable.PowerPack 1.3.0
Downloading Fable.Elmish.Debugger 1.0.0
Downloading NETStandard.Library 2.0.1
```

**Comment by VitalyBrusentsev** [comment]
@markpattison, `webpack.config.js` contains the following text:

```
// We don't need the polyfills as we're already calling
// cdn.polyfill.io/v2/polyfill.js in index.html
"polyfill": false,
```
If you replace it with
```
"polyfill": true,
```
, the sample will start working in IE11.

**Comment by MangelMaxime** [comment]
Yes, but then we are using twice the polyfill because I already included it in the index.html

But, seems to not be enough. I will update the template later with a new way to include the polyfills. Thanks for the confirmation @VitalyBrusentsev

**Comment by VitalyBrusentsev** [comment]
@MangelMaxime, it looks like this directive
```
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch"></script>
```
returns an empty script with a comment:
> /* No polyfills found for current settings */

If you replace it with
```
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=es6"></script>
```
, then the sample still works in IE11 with webpack.config.js unchanged.

**Comment by MangelMaxime** [comment]
Oh, I see perhaps I was thinking `default` to be enough but seems like it's not the case.

Thanks you :)

**Comment by markpattison** [comment]
Thanks both. I am happy to check this and send a PR for both demos later.
