### ISSUE TITLE
Warning during yarn install: fsevents@1.1.2: The platform "win32" is incompatible with this module.

### ISSUE THREAD

**Issue by 0x53A** [fable-elmish/templates#38]
``dotnet new fable-elmish-react -n AwesomeProject --yarn``

``yarn install``

```
yarn install v1.1.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
```

Is this something I should worry about, or is it expected?
If it is expected, should a small note be added to the readme?

**Comment by MangelMaxime** [comment]
There nothing to worry about this info log. 


It's coming from one of the dependencies and to be fair we have this info log on all 3 majors OS.

**Comment by 0x53A** [comment]
Ok thanks!
