### ISSUE TITLE
Only include Source Map during development

### ISSUE THREAD

**Issue by williamtetlow** [fable-elmish/templates#40]
I suggest we update the webpack config to only include the source map during development.

Change:
````
devtool: "source-map",
````

To:
````
devtool: isProduction ? "" : "source-map",
````

**Comment by MangelMaxime** [comment]
Sure, if you can send a PR.

Also, I think we should use `isProduction ? undefined : "source-map"`, to enter in the first case listed [in the doc](https://webpack.js.org/configuration/devtool/)

**Comment by williamtetlow** [comment]
Sorry got caught up with work, that's the PR opened^
