### ISSUE TITLE
Fulma instead of Bulma

### ISSUE THREAD

**Issue by williamtetlow** [fable-elmish/templates#45]
Could we replace Bulma with the F# wrapper Fulma? I think it'd be beneficial as it emphasises using bindings rather than literals.

I'm happy to do the work if we think it'd be a useful addition.

https://mangelmaxime.github.io/Fulma/#home

**Comment by MangelMaxime** [comment]
I am not sure we want to include Fulma_demo in the basic elmish templates because people could think it's the only way to use it.

We already have [fulma-demo](https://github.com/MangelMaxime/fulma-demo) has a great demo of both elmish and fulma.

**Comment by williamtetlow** [comment]
Good point, at least the package has been referenced in this project now incase anyone reads through the issues. I didn't know about fulma until I'd written a large part of my app. Will close the issue.

**Comment by MangelMaxime** [comment]
Yes, we have some problems to let users find Fable project. 

I am trying to work on a new version of Fable website, to help discovering new projects and make it more user friendly but still lot of work to do.
